from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field, replace
from types import MappingProxyType

from gwent_engine.ai.observations import (
    ObservedCard,
    ObservedRows,
    PlayerObservation,
    PublicPlayerStateView,
    VisiblePendingChoiceView,
)
from gwent_engine.ai.simulation.hidden_cards import (
    SIMULATION_HIDDEN_CARD_DEFINITION,
    provision_simulation_registry,
)
from gwent_engine.cards import CardRegistry
from gwent_engine.core import Row, Zone
from gwent_engine.core.actions import (
    GameAction,
    PlayCardAction,
    ResolveChoiceAction,
    UseLeaderAbilityAction,
)
from gwent_engine.core.ids import CardInstanceId, PlayerId
from gwent_engine.core.state import (
    CardInstance,
    GameState,
    LeaderState,
    PendingChoice,
    PlayerState,
    RowState,
)
from gwent_engine.leaders import LeaderRegistry


@dataclass(frozen=True, slots=True)
class PlayerSimulation:
    """Reducer-compatible state derived exclusively from a `PlayerObservation`.

    The simulation keeps exact viewer-hand and public identities, replaces every
    hidden opponent zone with generic placeholders, and rebuilds the viewer's
    own deck from the canonicalized composition. Instance ids for hidden zones
    are freshly generated by zone and ordinal, so they cannot encode
    authoritative card or draw-position identities.
    """

    state: GameState
    card_registry: CardRegistry
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId]

    def translate_action(self, action: GameAction) -> GameAction:
        """Remap viewer-deck references onto the simulation's synthetic ids."""

        return _translate_action(action, deck_instance_map=self.deck_instance_map)


def materialize_player_simulation(
    observation: PlayerObservation,
    *,
    card_registry: CardRegistry,
    leader_registry: LeaderRegistry | None = None,
) -> PlayerSimulation:
    del leader_registry
    registry = provision_simulation_registry(card_registry)
    viewer_public, opponent_public = _resolve_player_views(observation)
    public = observation.public_state
    builder = _SimulationBuilder()

    viewer_state = _player_state(
        viewer_public,
        hand=builder.observed_cards(observation.viewer_hand, zone=Zone.HAND),
        deck=builder.viewer_deck(observation, owner=viewer_public.player_id),
        discard=builder.observed_cards(viewer_public.discard, zone=Zone.DISCARD),
        rows=builder.observed_rows(viewer_public.rows, zone=Zone.BATTLEFIELD),
    )
    opponent_state = _player_state(
        opponent_public,
        hand=builder.hidden_cards(
            owner=opponent_public.player_id,
            zone=Zone.HAND,
            count=opponent_public.hand_count,
            prefix="opponent_hidden_hand",
        ),
        deck=builder.hidden_cards(
            owner=opponent_public.player_id,
            zone=Zone.DECK,
            count=opponent_public.deck_count,
            prefix="opponent_hidden_deck",
        ),
        discard=builder.observed_cards(opponent_public.discard, zone=Zone.DISCARD),
        rows=builder.observed_rows(opponent_public.rows, zone=Zone.BATTLEFIELD),
    )

    return PlayerSimulation(
        state=GameState(
            game_id=public.game_id,
            players=(viewer_state, opponent_state),
            card_instances=tuple(builder.instances),
            weather=builder.observed_rows(public.battlefield_weather, zone=Zone.WEATHER),
            pending_choice=_materialize_pending_choice(
                observation.visible_pending_choice,
                deck_instance_map=builder.deck_instance_map,
            ),
            current_player=public.current_player,
            starting_player=public.starting_player,
            round_starter=public.round_starter,
            round_number=public.round_number,
            phase=public.phase,
            status=public.status,
            match_winner=public.match_winner,
        ),
        card_registry=registry,
        deck_instance_map=MappingProxyType(builder.deck_instance_map),
    )


def _resolve_player_views(
    observation: PlayerObservation,
) -> tuple[PublicPlayerStateView, PublicPlayerStateView]:
    viewer_id = observation.viewer_player_id
    views = {player.player_id: player for player in observation.public_state.players}
    if len(views) != 2 or viewer_id not in views:
        raise ValueError("PlayerObservation must describe exactly two known players.")
    opponent_id = next(player_id for player_id in views if player_id != viewer_id)
    return views[viewer_id], views[opponent_id]


@dataclass(slots=True)
class _SimulationBuilder:
    """Collect the card instances and viewer-deck mapping for one simulation."""

    instances: list[CardInstance] = field(default_factory=list)
    deck_instance_map: dict[CardInstanceId, CardInstanceId] = field(default_factory=dict)

    def observed_cards(
        self,
        cards: tuple[ObservedCard, ...],
        *,
        zone: Zone,
        row: Row | None = None,
    ) -> tuple[CardInstanceId, ...]:
        instance_ids: list[CardInstanceId] = []
        for card in cards:
            instance_ids.append(card.instance_id)
            self.instances.append(
                CardInstance(
                    instance_id=card.instance_id,
                    definition_id=card.definition_id,
                    owner=card.owner,
                    zone=zone,
                    row=row,
                    battlefield_side=card.battlefield_side,
                )
            )
        return tuple(instance_ids)

    def observed_rows(self, rows: ObservedRows, *, zone: Zone) -> RowState:
        return RowState(
            close=self.observed_cards(rows.close, zone=zone, row=Row.CLOSE),
            ranged=self.observed_cards(rows.ranged, zone=zone, row=Row.RANGED),
            siege=self.observed_cards(rows.siege, zone=zone, row=Row.SIEGE),
        )

    def hidden_cards(
        self,
        *,
        owner: PlayerId,
        zone: Zone,
        count: int,
        prefix: str,
    ) -> tuple[CardInstanceId, ...]:
        instance_ids: list[CardInstanceId] = []
        for ordinal in range(1, count + 1):
            instance_id = CardInstanceId(f"{prefix}_{ordinal:03d}")
            instance_ids.append(instance_id)
            self.instances.append(
                CardInstance(
                    instance_id=instance_id,
                    definition_id=SIMULATION_HIDDEN_CARD_DEFINITION.definition_id,
                    owner=owner,
                    zone=zone,
                )
            )
        return tuple(instance_ids)

    def viewer_deck(
        self,
        observation: PlayerObservation,
        *,
        owner: PlayerId,
    ) -> tuple[CardInstanceId, ...]:
        instance_ids: list[CardInstanceId] = []
        for entry in observation.viewer_deck_composition:
            for authoritative_id in entry.instance_ids:
                synthetic_id = CardInstanceId(f"viewer_unknown_deck_{len(instance_ids) + 1:03d}")
                self.deck_instance_map[authoritative_id] = synthetic_id
                instance_ids.append(synthetic_id)
                self.instances.append(
                    CardInstance(
                        instance_id=synthetic_id,
                        definition_id=entry.definition_id,
                        owner=owner,
                        zone=Zone.DECK,
                    )
                )
        return tuple(instance_ids)


def _player_state(
    player: PublicPlayerStateView,
    *,
    hand: tuple[CardInstanceId, ...],
    deck: tuple[CardInstanceId, ...],
    discard: tuple[CardInstanceId, ...],
    rows: RowState,
) -> PlayerState:
    return PlayerState(
        player_id=player.player_id,
        faction=player.faction,
        leader=LeaderState(
            leader_id=player.leader.leader_id,
            used=player.leader.used,
            disabled=player.leader.disabled,
            horn_row=player.leader.horn_row,
        ),
        deck=deck,
        hand=hand,
        discard=discard,
        rows=rows,
        gems_remaining=player.gems_remaining,
        round_wins=player.round_wins,
        has_passed=player.has_passed,
    )


def _materialize_pending_choice(
    visible: VisiblePendingChoiceView | None,
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> PendingChoice | None:
    if visible is None:
        return None
    return PendingChoice(
        choice_id=visible.choice_id,
        player_id=visible.player_id,
        kind=visible.kind,
        source_kind=visible.source_kind,
        source_card_instance_id=_translate_optional(
            visible.source_card_instance_id,
            deck_instance_map=deck_instance_map,
        ),
        source_leader_id=visible.source_leader_id,
        legal_target_card_instance_ids=_translate_ids(
            visible.legal_target_card_instance_ids,
            deck_instance_map=deck_instance_map,
        ),
        legal_rows=visible.legal_rows,
        min_selections=visible.min_selections,
        max_selections=visible.max_selections,
        source_row=visible.source_row,
    )


def _translate_action(
    action: GameAction,
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> GameAction:
    match action:
        case PlayCardAction():
            return replace(
                action,
                card_instance_id=_translate_id(
                    action.card_instance_id,
                    deck_instance_map=deck_instance_map,
                ),
                target_card_instance_id=_translate_optional(
                    action.target_card_instance_id,
                    deck_instance_map=deck_instance_map,
                ),
                secondary_target_card_instance_id=_translate_optional(
                    action.secondary_target_card_instance_id,
                    deck_instance_map=deck_instance_map,
                ),
            )
        case UseLeaderAbilityAction():
            return replace(
                action,
                target_card_instance_id=_translate_optional(
                    action.target_card_instance_id,
                    deck_instance_map=deck_instance_map,
                ),
                secondary_target_card_instance_id=_translate_optional(
                    action.secondary_target_card_instance_id,
                    deck_instance_map=deck_instance_map,
                ),
                selected_card_instance_ids=_translate_ids(
                    action.selected_card_instance_ids,
                    deck_instance_map=deck_instance_map,
                ),
            )
        case ResolveChoiceAction():
            return replace(
                action,
                selected_card_instance_ids=_translate_ids(
                    action.selected_card_instance_ids,
                    deck_instance_map=deck_instance_map,
                ),
            )
        case _:
            return action


def _translate_ids(
    card_ids: Sequence[CardInstanceId],
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> tuple[CardInstanceId, ...]:
    return tuple(
        _translate_id(card_id, deck_instance_map=deck_instance_map) for card_id in card_ids
    )


def _translate_id(
    card_id: CardInstanceId,
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> CardInstanceId:
    return deck_instance_map.get(card_id, card_id)


def _translate_optional(
    card_id: CardInstanceId | None,
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> CardInstanceId | None:
    if card_id is None:
        return None
    return _translate_id(card_id, deck_instance_map=deck_instance_map)
