from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, replace
from types import MappingProxyType

from gwent_engine.ai.observations import (
    ObservedCard,
    ObservedRows,
    PlayerObservation,
    PublicPlayerStateView,
    VisiblePendingChoiceView,
)
from gwent_engine.ai.simulation.hidden_cards import (
    SIMULATION_HIDDEN_CARD_DEFINITION,
    provision_simulation_registry,
)
from gwent_engine.cards import CardRegistry
from gwent_engine.core import Row, Zone
from gwent_engine.core.actions import (
    GameAction,
    PlayCardAction,
    ResolveChoiceAction,
    UseLeaderAbilityAction,
)
from gwent_engine.core.ids import CardInstanceId, PlayerId
from gwent_engine.core.state import (
    CardInstance,
    GameState,
    LeaderState,
    PendingChoice,
    PlayerState,
    RowState,
)
from gwent_engine.leaders import LeaderRegistry


@dataclass(frozen=True, slots=True)
class PlayerSimulation:
    """Reducer-compatible state derived exclusively from a `PlayerObservation`.

    The simulation keeps exact viewer-hand and public identities, replaces every
    hidden opponent zone with generic placeholders, and rebuilds the viewer's
    own deck from the canonicalized composition. Instance ids for hidden zones
    are freshly generated by zone and ordinal, so they cannot encode
    authoritative card or draw-position identities.
    """

    state: GameState
    card_registry: CardRegistry
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId]

    def translate_action(self, action: GameAction) -> GameAction:
        """Remap viewer-deck references onto the simulation's synthetic ids."""

        match action:
            case PlayCardAction():
                return replace(
                    action,
                    card_instance_id=self._translate_id(action.card_instance_id),
                    target_card_instance_id=self._translate_optional(
                        action.target_card_instance_id
                    ),
                    secondary_target_card_instance_id=self._translate_optional(
                        action.secondary_target_card_instance_id
                    ),
                )
            case UseLeaderAbilityAction():
                return replace(
                    action,
                    target_card_instance_id=self._translate_optional(
                        action.target_card_instance_id
                    ),
                    secondary_target_card_instance_id=self._translate_optional(
                        action.secondary_target_card_instance_id
                    ),
                    selected_card_instance_ids=tuple(
                        self._translate_id(card_id) for card_id in action.selected_card_instance_ids
                    ),
                )
            case ResolveChoiceAction():
                return replace(
                    action,
                    selected_card_instance_ids=tuple(
                        self._translate_id(card_id) for card_id in action.selected_card_instance_ids
                    ),
                )
            case _:
                return action

    def _translate_id(self, card_id: CardInstanceId) -> CardInstanceId:
        return self.deck_instance_map.get(card_id, card_id)

    def _translate_optional(self, card_id: CardInstanceId | None) -> CardInstanceId | None:
        return None if card_id is None else self._translate_id(card_id)


def materialize_player_simulation(
    observation: PlayerObservation,
    *,
    card_registry: CardRegistry,
    leader_registry: LeaderRegistry | None = None,
) -> PlayerSimulation:
    del leader_registry
    registry = provision_simulation_registry(card_registry)
    viewer_id = observation.viewer_player_id
    public = observation.public_state
    player_views = {player.player_id: player for player in public.players}
    if viewer_id not in player_views or len(player_views) != 2:
        raise ValueError("PlayerObservation must describe exactly two known players.")
    opponent_id = next(player_id for player_id in player_views if player_id != viewer_id)
    viewer_public = player_views[viewer_id]
    opponent_public = player_views[opponent_id]

    instances: list[CardInstance] = []
    viewer_hand_ids = _append_observed_zone_instances(
        observation.viewer_hand,
        zone=Zone.HAND,
        instances=instances,
    )
    viewer_deck_ids, deck_instance_map = _append_viewer_deck_instances(
        observation,
        viewer_id=viewer_id,
        instances=instances,
    )
    opponent_hand_ids = _append_hidden_zone_instances(
        owner=opponent_id,
        zone=Zone.HAND,
        count=opponent_public.hand_count,
        prefix="opponent_hidden_hand",
        instances=instances,
    )
    opponent_deck_ids = _append_hidden_zone_instances(
        owner=opponent_id,
        zone=Zone.DECK,
        count=opponent_public.deck_count,
        prefix="opponent_hidden_deck",
        instances=instances,
    )

    viewer_rows = _append_observed_rows(
        viewer_public.rows,
        zone=Zone.BATTLEFIELD,
        instances=instances,
    )
    viewer_discard_ids = _append_observed_zone_instances(
        viewer_public.discard,
        zone=Zone.DISCARD,
        instances=instances,
    )
    opponent_rows = _append_observed_rows(
        opponent_public.rows,
        zone=Zone.BATTLEFIELD,
        instances=instances,
    )
    opponent_discard_ids = _append_observed_zone_instances(
        opponent_public.discard,
        zone=Zone.DISCARD,
        instances=instances,
    )
    weather = _append_observed_rows(
        public.battlefield_weather,
        zone=Zone.WEATHER,
        instances=instances,
    )

    return PlayerSimulation(
        state=GameState(
            game_id=public.game_id,
            players=(
                _player_state(
                    viewer_public,
                    hand=viewer_hand_ids,
                    deck=viewer_deck_ids,
                    discard=viewer_discard_ids,
                    rows=viewer_rows,
                ),
                _player_state(
                    opponent_public,
                    hand=opponent_hand_ids,
                    deck=opponent_deck_ids,
                    discard=opponent_discard_ids,
                    rows=opponent_rows,
                ),
            ),
            card_instances=tuple(instances),
            weather=weather,
            pending_choice=_materialize_pending_choice(
                observation.visible_pending_choice,
                deck_instance_map=deck_instance_map,
            ),
            current_player=public.current_player,
            starting_player=public.starting_player,
            round_starter=public.round_starter,
            round_number=public.round_number,
            phase=public.phase,
            status=public.status,
            match_winner=public.match_winner,
        ),
        card_registry=registry,
        deck_instance_map=MappingProxyType(deck_instance_map),
    )


def _append_viewer_deck_instances(
    observation: PlayerObservation,
    *,
    viewer_id: PlayerId,
    instances: list[CardInstance],
) -> tuple[tuple[CardInstanceId, ...], dict[CardInstanceId, CardInstanceId]]:
    deck_ids: list[CardInstanceId] = []
    instance_map: dict[CardInstanceId, CardInstanceId] = {}
    ordinal = 0
    for entry in observation.viewer_deck_composition:
        for authoritative_id in entry.instance_ids:
            ordinal += 1
            synthetic_id = CardInstanceId(f"viewer_unknown_deck_{ordinal:03d}")
            instance_map[authoritative_id] = synthetic_id
            deck_ids.append(synthetic_id)
            instances.append(
                CardInstance(
                    instance_id=synthetic_id,
                    definition_id=entry.definition_id,
                    owner=viewer_id,
                    zone=Zone.DECK,
                )
            )
    return tuple(deck_ids), instance_map


def _append_hidden_zone_instances(
    *,
    owner: PlayerId,
    zone: Zone,
    count: int,
    prefix: str,
    instances: list[CardInstance],
) -> tuple[CardInstanceId, ...]:
    hidden_ids: list[CardInstanceId] = []
    for ordinal in range(1, count + 1):
        instance_id = CardInstanceId(f"{prefix}_{ordinal:03d}")
        hidden_ids.append(instance_id)
        instances.append(
            CardInstance(
                instance_id=instance_id,
                definition_id=SIMULATION_HIDDEN_CARD_DEFINITION.definition_id,
                owner=owner,
                zone=zone,
            )
        )
    return tuple(hidden_ids)


def _append_observed_zone_instances(
    cards: tuple[ObservedCard, ...],
    *,
    zone: Zone,
    instances: list[CardInstance],
) -> tuple[CardInstanceId, ...]:
    observed_ids: list[CardInstanceId] = []
    for card in cards:
        observed_ids.append(card.instance_id)
        instances.append(
            CardInstance(
                instance_id=card.instance_id,
                definition_id=card.definition_id,
                owner=card.owner,
                zone=zone,
            )
        )
    return tuple(observed_ids)


def _append_observed_rows(
    observed_rows: ObservedRows,
    *,
    zone: Zone,
    instances: list[CardInstance],
) -> RowState:
    row_ids: dict[Row, tuple[CardInstanceId, ...]] = {}
    for row, cards in (
        (Row.CLOSE, observed_rows.close),
        (Row.RANGED, observed_rows.ranged),
        (Row.SIEGE, observed_rows.siege),
    ):
        row_instance_ids: list[CardInstanceId] = []
        for card in cards:
            row_instance_ids.append(card.instance_id)
            instances.append(
                CardInstance(
                    instance_id=card.instance_id,
                    definition_id=card.definition_id,
                    owner=card.owner,
                    zone=zone,
                    row=row,
                    battlefield_side=card.battlefield_side,
                )
            )
        row_ids[row] = tuple(row_instance_ids)
    return RowState(
        close=row_ids[Row.CLOSE],
        ranged=row_ids[Row.RANGED],
        siege=row_ids[Row.SIEGE],
    )


def _player_state(
    player: PublicPlayerStateView,
    *,
    hand: tuple[CardInstanceId, ...],
    deck: tuple[CardInstanceId, ...],
    discard: tuple[CardInstanceId, ...],
    rows: RowState,
) -> PlayerState:
    return PlayerState(
        player_id=player.player_id,
        faction=player.faction,
        leader=LeaderState(
            leader_id=player.leader.leader_id,
            used=player.leader.used,
            disabled=player.leader.disabled,
            horn_row=player.leader.horn_row,
        ),
        deck=deck,
        hand=hand,
        discard=discard,
        rows=rows,
        gems_remaining=player.gems_remaining,
        round_wins=player.round_wins,
        has_passed=player.has_passed,
    )


def _materialize_pending_choice(
    visible: VisiblePendingChoiceView | None,
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> PendingChoice | None:
    if visible is None:
        return None
    return PendingChoice(
        choice_id=visible.choice_id,
        player_id=visible.player_id,
        kind=visible.kind,
        source_kind=visible.source_kind,
        source_card_instance_id=_translate_optional(
            visible.source_card_instance_id,
            deck_instance_map=deck_instance_map,
        ),
        source_leader_id=visible.source_leader_id,
        legal_target_card_instance_ids=tuple(
            _translate_id(card_id, deck_instance_map=deck_instance_map)
            for card_id in visible.legal_target_card_instance_ids
        ),
        legal_rows=visible.legal_rows,
        min_selections=visible.min_selections,
        max_selections=visible.max_selections,
        source_row=visible.source_row,
    )


def _translate_id(
    card_id: CardInstanceId,
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> CardInstanceId:
    return deck_instance_map.get(card_id, card_id)


def _translate_optional(
    card_id: CardInstanceId | None,
    *,
    deck_instance_map: Mapping[CardInstanceId, CardInstanceId],
) -> CardInstanceId | None:
    if card_id is None:
        return None
    return _translate_id(card_id, deck_instance_map=deck_instance_map)
